### ISSUE TITLE
Should have all routes available

### ISSUE THREAD

**Issue by juliancoleman** [juliancoleman/vigor#2]
Well, to start, we are going to need some routes. I've started to add some, that I will push to master, unfortunately, but I will PR from here on out. I wasn't expecting to do as much work as I did tonight.

**Comment by juliancoleman** [comment]
I'm thinking the routes should go as follows. Let me know what you think @jadengore 
- Index

> if !loggedIn
> if NewVisitor
> note: should describe Vigor App and its capabilities.
- Login

> if !loggedIn
> onSubmit = { redirectTo: "/dashboard" }
- Signup

> if userNotFoundInDatabase
> onSubmit = { redirectTo: "/dashboard" }
- Dashboard

> should show full meal history
> should show DRI and daily progress
> no, we won't penalize you from taking a day off. It'll simply record 0/{DRI value} for that day.
- Profile

> should show user overview
- Add Meal

> onSubmit = { redirectTo: "/edit-meal" }
- Edit Meal

> to stop people from cheating, this is a misleading endpoint. It's to finalize in case there was misinformation on `add-meal` before finally submitting

**Comment by ebramanti** [comment]
@juliancoleman Try to break each of these down into stories instead of their routes, I'll help you with one:

> A user should be able to log into Vigor

In the description of that story you can add as much or as little as you want. We call this sprint planning, where we shove a bunch of stuff into the product's backlog and then we cherry pick what we want to do in sprints so you don't get overwhelmed.

**Comment by juliancoleman** [comment]
I know. I just wanted to get the list of routes. I will break them down individually. But I know what you mean. I may just throw this issue and create several others when I get the chance

**Comment by ebramanti** [comment]
@juliancoleman Don't worry about trying to map all the routes, take the pieces of functionality one at a time and create routes as needed. Right now, you just need a way to execute your business rules.

The best form of organization is user stories.

See more here about how to set up your product backlog: https://www.atlassian.com/agile/backlogs
